### ISSUE TITLE
Soon Website

### ISSUE THREAD

**Issue by jasurhaydarovcode** [jasurhaydarovcode/IDM#26]
# Cooming soon **website**. How to work project

**Comment by Gokul-Selva-105** [comment]
i am eagerly waiting bro

**Comment by jasurhaydarovcode** [comment]
### I'm Started 😊
![image](https://github.com/user-attachments/assets/441455c2-0cd5-4ca3-b747-eb887f159155)

**Comment by jasurhaydarovcode** [comment]
website ready, and video ready 😊
